# Generated by Django 5.1.6 on 2025-03-01 12:52

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_extenduser_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='my_group_name',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('id', models.Value('G'), 'channel_name'), output_field=models.CharField(blank=True, max_length=100, null=True)),
        ),
    ]
