# Generated by Django 5.1.6 on 2025-03-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_extenduser_my_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extenduser',
            name='my_group_name',
        ),
    ]
