# Generated by Django 5.1.6 on 2025-03-01 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_extenduser_my_group_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friendship',
        ),
    ]
