# Generated by Django 5.1.6 on 2025-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_friends_friendship'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['person'], name='chat_friend_person__b3c1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['friend'], name='chat_friend_friend__94a393_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('person', 'friend'), name='person_friend'),
        ),
    ]
