# Generated by Django 5.1.6 on 2025-03-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='group_name', to='chat.groups'),
            preserve_default=False,
        ),
    ]
