# Generated by Django 5.1.6 on 2025-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_friendrequest'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('person', 'friend', 'group'), name='person_friend_group'),
        ),
    ]
