# Generated by Django 5.1.6 on 2025-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_friendship_person_friend_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
