# Generated by Django 5.1.6 on 2025-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_extenduser_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['group'], name='chat_friend_group_i_f86cb3_idx'),
        ),
    ]
