# Generated by Django 5.1.6 on 2025-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_friendship_chat_friend_group_i_f86cb3_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, related_name='message', to='chat.file'),
        ),
    ]
