# Generated by Django 5.1.6 on 2025-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_file_messages_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
