# Generated by Django 5.1.6 on 2025-03-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_messages_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='message',
        ),
    ]
