# Generated by Django 5.1.6 on 2025-03-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_content_messages_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='files',
            field=models.ManyToManyField(related_name='message', to='chat.file'),
        ),
    ]
