# Generated by Django 5.1.6 on 2025-03-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_messages_files'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='messages',
            constraint=models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='unique_sender_receiver', violation_error_message='Message, sender and\n                receiver can not be same.'),
        ),
    ]
